
export const motivationalQuotes = [
  "Pequenas ações geram grandes resultados.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Acredite em você e tudo será possível.",
  "A persistência realiza o impossível.",
  "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
  "Comece onde você está. Use o que você tem. Faça o que você pode.",
  "Não espere por oportunidades, crie-as.",
  "Sua única limitação é você mesmo.",
  "A jornada de mil quilômetros começa com um único passo.",
  "A disciplina é a ponte entre metas e realizações.",
  "Se você pode sonhar, você pode fazer.",
  "A melhor maneira de prever o futuro é criá-lo.",
  "O fracasso é apenas a oportunidade de recomeçar de forma mais inteligente.",
  "Acreditar é a força que nos permite subir os maiores degraus na escada da vida.",
  "Mire na lua. Mesmo que você erre, você ainda estará entre as estrelas.",
  "A força de vontade deve ser mais forte do que a habilidade.",
  "Para ter sucesso, o seu desejo de sucesso deve ser maior do que o seu medo do fracasso.",
  "Não se desespere, confie em si mesmo.",
  "O otimismo é o imã da felicidade. Se você for positivo, coisas boas e pessoas boas serão atraídas a você.",
  "O talento vence jogos, mas o trabalho em equipe e a inteligência vencem campeonatos.",
  "Um objetivo sem um plano é apenas um desejo.",
  "A motivação é o que faz você começar. O hábito é o que faz você continuar.",
  "A vida é 10% o que acontece com você e 90% como você reage a isso.",
  "Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado.",
  "A coragem não é a ausência de medo, mas a persistência apesar do medo.",
  "Transforme suas feridas em sabedoria.",
  "O segredo para progredir é começar.",
  "Você nunca sabe que resultados virão da sua ação. Mas se você não fizer nada, não existirão resultados.",
  "Quanto mais você trabalha, mais sorte você tem.",
  "Um dia você vai olhar para trás e ver que os problemas eram, na verdade, os degraus que te levaram à vitória.",
];
